### ISSUE TITLE
Learn About Magical Unicorns, Space Monkeys and Rainbows.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#12]
I have a feeling there is going to be crafty design stuff coming up and I want my ninja army to be prepared for the tasks at hand. 
1. You shall not fear SVG because you will have acquired the knowledge of where to find Magical Unicorns
   
   This is the best gathering of unicorns I have found: 
   
   https://github.com/filamentgroup/grunticon
   
   This is the first I knew about:
   
   http://css-tricks.com/svg-sprites-use-better-icon-fonts/
   
   Different types of unicorns:
   
   https://icomoon.io/
   http://fortawesome.github.io/Font-Awesome/
   https://fonticons.com
2. Space Monkeys
   
   DONT write CSS prefixes by hand like in this space monkeys example ever again:
   
   http://codepen.io/minimalmonkey/pen/maLgs
   
   DO use autoprefixer and write 100% standards compliant CSS:
   
   http://css-tricks.com/autoprefixer/
   
   Autoprefixer VS LESS/SASS mixin?
   - Postprocessors rock! https://github.com/postcss/postcss
   - Google agrees https://developers.google.com/web/fundamentals/tools/build/setupbuildprocess#dont-trip-up-with-vendor-prefixes
   - It reads the same reference as we humans do http://caniuse.com/ 
3. Rainbows:
   
   Don't be afraid to look for rainbows. They help expand your mind and see new solutions, be more creative. And the colour is soothing. It's all about looking in the right places unlike Larry Laffer when he's looking for love. 
   
   Right places are: Package Registries (npmjs.org,bower.io,packagist.org, etc..), Code Repositories ( github, bitbucket, etc...) and Linux Packages (aptitude,pacman).
   
   As an exercise, you can literally look for rainbows, you'll be surprised what fun things you can find:
   - https://www.npmjs.com/search?q=rainbows
   - http://bower.io/search/?q=rainbow
   - https://packagist.org/search/?q=rainbows
   - `ubuntu$ sudo apt-cache search rainbows` 

Arch Linux: ( yaourt -Ss rainbows )

```
aur/lolcat 42.0.99-3 (14)
    Okay, no unicorns. But rainbows!!
aur/ruby-rainbows 4.6.2-1 (0)
    Unicorn for sleepy apps and slow clients
```

**Comment by AKRFranko** [comment]
brew search rainbows?

**Comment by pom2ter** [comment]
done (but nothing in brew :( )
