### ISSUE TITLE
Start With One Ecommerce Plugin

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#20]
On a besoin de choisir au moins un plugin e-commerec pour partir le bal car tout les designs incluent des items d'un "product catalog".

Peut importe lequel on choisit, on est pas "pris" avec, mais au moins si on dois changer de strategie on pourra quand meme re-utiliser les templates.

A date je crois que WP Ecommerce est plus facile a comprendre. Mais cote "features" c'est difficile a dire. 

|  | WooCommerce | WP eCommerce |
| --- | --- | --- |
| Shopping Features |  |  |
| Coupons and Discounts | (free) | (free) |
| Product Reviews | (free) | (addon) |
| Subscriptions / Recurring Payments | (addon) | (addon) |
| Simple Shipping | (free) | (free) |
| Advanced / Table Rate Shipping | (addon) | (free) |
| Shipment Tracking | (addon) | ? |
| License Keys / Software Sale | (addon) | ? |
| Manual Purchases | (free) | (free) |
| Cross-sell and Upsell | (addon) | ? |
| PDF Invoices | (addon) | (addon) |
| Suggestions / Related Products | (addon) | (addon) |
| Product Comparisons | (addon) | ? |
|  | WooCommerce | WP eCommerce |
| Payment Processors |  |  |
| Paypal Standard | (free) | (free) |
| Paypal Express / Pro | (addon) | (addon) |
| Stripe | (addon) | (addon) |
| Authorize.net | (addon) | (addon) |
| 2Checkout | (addon) | ? |
| WorldPay | (addon) | ? |
| Braintree | (addon) | (addon) |
| FirstData | (addon) | (addon) |
| Amazon Payments | (addon) | ? |
| Skrill / Moneybookers | (addon) | ? |
| Google Checkout | (addon) | ? |
| SagePay | (addon) | (addon) |
| Mijireh | (free) | ? |
|  | WooCommerce | WP eCommerce |
| Email Integrations |  |  |
| MailChimp | (addon) | (addon) |
| Constant Contact | (addon) | ? |
| Mad Mimi | (addon) | ? |
| Aweber | (addon) | ? |
| Campaign Monitor | (addon) | (free) |
| GetResponse | (free) | ? |
|  | WooCommerce | WP eCommerce |
| Invoicing, Shipping and Misc Integrations |  |  |
| FedEx Shipping Costs | (addon) | (addon) |
| UPS Shipping Costs | (addon) | (free) |
| USPS | (addon) | (free) |
| Freshdesk | (addon) | ? |
| FreshBooks | (addon) | ? |
| FastBill |  | ? |
| QuickBooks | (addon) | ? |
| Zapier | (addon) | ? |
| Amazon S3 | (addon) | (addon) |
|  | WooCommerce | WP eCommerce |
| Niche And Other Features |  |  |
| Bookings / Time and Date Based Orders | (addon) | ? |
| 3rd Party Vendors / Product Submission | (addon) | (free) |
| Wishlists | (addon) | (addon) |
| Address Validation | (addon) | ? |
| Product CSV Import | (addon) | (addon) |
| EU Vat ID Collection | (addon) | ? |
| Social Discounts (for Sharing or Reviewing) | (addon) | ? |
| Image Watermarks | (addon) | ? |
| Points / Rewards System | (addon) | ? |
| Support Forums / bbPress Integration | (addon) | ? |

cc /@AKRFranko

**Comment by pom2ter** [comment]
Il y a pas grand différence entre les 2 mais je penche plus vers woocommerce juste parce que l'admin est plus user friendly (pour le client), sa plus grande communauté, meilleur 'customer support' et le plugin est sur github, mais c'est plus une question de gout que d'autre chose

**Comment by AKRFranko** [comment]
woo it is!
