### ISSUE TITLE
Do you have GPG?

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#21]
```
$ gpg --version
```

**Comment by pom2ter** [comment]
no i dont

**Comment by AKRFranko** [comment]
brew? (gnupg || gpg) ?

**Comment by pom2ter** [comment]
jai le choix entre gpg, gpg2, gpg-agent, gpgme, libgpg-error

**Comment by AKRFranko** [comment]
gpg

**Comment by pom2ter** [comment]
gpg version 1.4.18

**Comment by AKRFranko** [comment]
```
gpg --gen-key
```

**Comment by AKRFranko** [comment]
1 RSA

**Comment by AKRFranko** [comment]
2048 bits

**Comment by AKRFranko** [comment]
0 does not expire

**Comment by AKRFranko** [comment]
y

**Comment by AKRFranko** [comment]
gpg --export -a "Real Name" > gpg-public.key

(Where Real Name is what you put earlier) Send me that file. 

also send me 

   ~/.ssh/ta_cle.pub 

cld be id_rsa.pub or id_dsa.pub or something_else.pub

**Comment by pom2ter** [comment]
par email ?

**Comment by AKRFranko** [comment]
worksforme!

**Comment by AKRFranko** [comment]
Try to zip them if it's not too late!

**Comment by pom2ter** [comment]
too late

**Comment by AKRFranko** [comment]
Nice. J'va pas necessairement me servir de la gpg mais je l'ai au cas ou je veut t<Envoyer des documents encryptes.
