### ISSUE TITLE
Test that the hosting setup is functional.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#22]
Logon to http://elementdebase.com/wp-admin

User: developer
Password: <sent via SMS>

Confirmer Que:
1. On peut installer un plugin via l'admin
2. On peut installer un theme via l'admin
3. On peut creer des posts, des pages, des comments
4. On peut telecharger des images etc...
5. Essayes d'installer woocommerce, taponne avec un peu voir si il lui manque des php dependencies

Ecris mois tes resultats dans ce ticket, point par point. (One comment or multiple, don't care)

**Comment by pom2ter** [comment]
Pas de problèmes avec les 4 premiers points.
point 5, il y a un warning pour la limite de mémoire de php (a changer dans php.ini) 64mb est recommandé.
et un autre warning pour la classe client SOAP  ( http://php.net/manual/en/class.soapclient.php ) utilisé par certains plugins

**Comment by AKRFranko** [comment]
Thx!
