### ISSUE TITLE
Kick off catalog / data structure.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#24]
- Look at data structure and relationships.
- Figure out how far woo plugin handles this.
- Attempt a first product catalog implementation with woo so devs can theme.

**Comment by AKRFranko** [comment]
| SKUs |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | nb of: |  |  |  |  |  |  |  |
| Model name | Orientation | Colors/finishings |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |
| Flex | 1 | 14 |  |  |  |  |  | 14 |
| Maritime 3 seat | 1 | 14 |  |  |  |  |  | 14 |
| Maritime 2 seat | 1 | 14 |  |  |  |  |  | 14 |
| Maritime 1 seat | 1 | 14 |  |  |  |  |  | 14 |
| Maritime Ottoman | 1 | 14 |  |  |  |  |  | 14 |
| Maritime wood legs cylinder | 1 | 1 |  |  |  |  |  | 1 |
| Martime wood legs v-shape | 1 | 1 |  |  |  |  |  | 1 |
| Madrid composition 1 | 1 | 14 |  |  |  |  |  | 14 |
| Madrid composition 2 | 1 | 14 |  |  |  |  |  | 14 |
| Madrid composition 3 | 1 | 14 |  |  |  |  |  | 14 |
| Madrid corner | 1 | 14 |  |  |  |  |  | 14 |
| Madrid single | 1 | 14 |  |  |  |  |  | 14 |
| Madrid Ottoman | 1 | 14 |  |  |  |  |  | 14 |
| Madrid Half cercle | 1 | 14 |  |  |  |  |  | 14 |
| Expo | 2 | 14 |  |  |  |  |  | 28 |
| Panorama | 2 | 14 |  |  |  |  |  | 28 |
| Atrium Sectional | 2 | 14 |  |  |  |  |  | 28 |
| Atrium 3-seat | 1 | 14 |  |  |  |  |  | 14 |
| Atrium 2 seat | 1 | 14 |  |  |  |  |  | 14 |
| Piqué sectional | 2 | 14 |  |  |  |  |  | 28 |
| Bean sectional | 1 | 14 |  |  |  |  |  | 14 |
| Bean corner | 1 | 14 |  |  |  |  |  | 14 |
| Bean Single | 1 | 14 |  |  |  |  |  | 14 |
| Bean Pool | 1 | 14 |  |  |  |  |  | 14 |
| Waffle sectional | 2 | 14 |  |  |  |  |  | 28 |
| Taxi 1 seat | 1 | 14 |  |  |  |  |  | 14 |
| Taxi 2 seat | 1 | 14 |  |  |  |  |  | 14 |
| Taxi 3 seat | 1 | 14 |  |  |  |  |  | 14 |
| Tight seat tight back base 1 seat | 2 | 14 |  |  |  |  |  | 28 |
| Stripes 3 seat | 1 | 14 |  |  |  |  |  | 14 |
| Stripes 2 seat | 1 | 14 |  |  |  |  |  | 14 |
| Chesterfield 3 seat | 1 | 14 |  |  |  |  |  | 14 |
| Chesterfield 2 seat | 1 | 14 |  |  |  |  |  | 14 |
| Sloped arm 3 seat | 1 | 14 |  |  |  |  |  | 14 |
| Sloped arm 2 seat | 1 | 14 |  |  |  |  |  | 14 |
| William 3 seat | 1 | 14 |  |  |  |  |  | 14 |
| William 2 seat | 1 | 14 |  |  |  |  |  | 14 |
| William 1 seat | 1 | 14 |  |  |  |  |  | 14 |
| Roll arm 3 seat | 1 | 14 |  |  |  |  |  | 14 |
| Roll arm 2 seat | 1 | 14 |  |  |  |  |  | 14 |
| Roll arm 1 seat | 1 | 14 |  |  |  |  |  | 14 |
| Vanguard 2 | 2 | 14 |  |  |  |  |  | 28 |
| Blazys | 1 | 14 |  |  |  |  |  | 14 |
| Blazys | 1 | 14 |  |  |  |  |  | 14 |
|  |  |  |  |  |  |  |  |  |
| Sofa bed clic clac | 1 | 14 |  |  |  |  |  | 14 |
| Cactus | 1 | 14 |  |  |  |  |  | 14 |
| Sectional sofa bed | 2 | 14 |  |  |  |  |  | 28 |
|  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |
| Small round | 1 | 14 |  |  |  |  |  | 14 |
| Oreilles single | 1 | 14 |  |  |  |  |  | 14 |
| Koala | 1 | 14 |  |  |  |  |  | 14 |
| No arm single | 1 | 14 |  |  |  |  |  | 14 |
| No arm single base | 1 | 3 |  |  |  |  |  | 3 |
| Wait | 1 | 14 |  |  |  |  |  | 14 |
| Wait base | 1 | 3 |  |  |  |  |  | 3 |
| Derek | 1 | 14 |  |  |  |  |  | 14 |
| Derek base | 1 | 3 |  |  |  |  |  | 3 |
|  |  |  |  |  |  |  |  |  |
| Bench top 60" | 1 | 1 |  |  |  |  |  | 1 |
| Bench top 30" | 1 | 1 |  |  |  |  |  | 1 |
| Base for bench | 1 | 4 |  |  |  |  |  | 4 |
| Block | 1 | 1 |  |  |  |  |  | 1 |
| C-table plexi | 1 | 3 |  |  |  |  |  | 3 |
| Triangle | 1 | 1 |  |  |  |  |  | 1 |
| Three legged stool | 1 | 3 |  |  |  |  |  | 3 |
| Tabouret table | 1 | 3 |  |  |  |  |  | 3 |
| Round | 1 | 4 |  |  |  |  |  | 4 |
| Mickey mouse | 1 | 3 |  |  |  |  |  | 3 |
| Pouf carré | 1 | 14 |  |  |  |  |  | 14 |
| Table pouf carré | 1 | 1 |  |  |  |  |  | 1 |
| A | 1 | 3 |  |  |  |  |  | 3 |
| B | 1 | 3 |  |  |  |  |  | 3 |
| C | 1 | 3 |  |  |  |  |  | 3 |
|  |  |  |  |  |  |  |  |  |
| Cushion 1 | 1 | 3 |  |  |  |  |  | 3 |
| Cushion 2 | 1 | 5 |  |  |  |  |  | 5 |
| Cushion 3 | 1 | 6 |  |  |  |  |  | 6 |
| Cushion 4 | 1 | 14 |  |  |  |  |  | 14 |
| Cushion 5 | 1 | 3 |  |  |  |  |  | 3 |
|  |  |  |  |  |  |  |  |  |
| Throw 1 | 1 | 3 |  |  |  |  |  | 3 |
|  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  | 919 |

**Comment by AKRFranko** [comment]
![page-0](https://cloud.githubusercontent.com/assets/7863981/6173576/14cf911c-b2b7-11e4-927e-c2b00c2fdd35.png)
![page-1](https://cloud.githubusercontent.com/assets/7863981/6173577/14d651c8-b2b7-11e4-8bd0-f5badd579460.png)
![page-2](https://cloud.githubusercontent.com/assets/7863981/6173578/14d6f6f0-b2b7-11e4-82d9-f5d49e5314a2.png)
![page-3](https://cloud.githubusercontent.com/assets/7863981/6173579/14dad374-b2b7-11e4-8eaf-db3e95e5e620.png)
![page-4](https://cloud.githubusercontent.com/assets/7863981/6173580/14dce376-b2b7-11e4-9a76-e27bbae3b0a1.png)
![page-5](https://cloud.githubusercontent.com/assets/7863981/6173581/14df2d70-b2b7-11e4-86bb-36d640af4a60.png)
![page-6](https://cloud.githubusercontent.com/assets/7863981/6173582/14e323da-b2b7-11e4-8cad-8e08d5a26636.png)
![page-7](https://cloud.githubusercontent.com/assets/7863981/6173583/14e9783e-b2b7-11e4-925e-35fce2f89dca.png)
![page-8](https://cloud.githubusercontent.com/assets/7863981/6173584/14ed9784-b2b7-11e4-9ac4-06cb30ebd75f.png)
![page-9](https://cloud.githubusercontent.com/assets/7863981/6173585/14f1c67e-b2b7-11e4-8b7a-dc7c818ae35e.png)

**Comment by AKRFranko** [comment]
```
                 +---------+   +-------------+  +-----------+  +------------+    +--------------+   +--------------------+   +------------------+  +-----------+   +--------------+          
                 | Sofas   |   | Sectionals  |  | Sofa Beds |  | Armchairs  |    | Coffe Tables |   | Benches / Ottomans |   | Headboards       |  | Storage   |   | Accessories  +---+      
    +--------+-------------+   +----+------+-+  +-----------+  +------------+    +--------------+   +--------------------+   +------------------+  +-----------+   +--+-------+---+   |      
    |        |   |                  |      |                                                                                                                          |       |       |      
    |        |   |                  |      +-----+    ^                                                                                                               |       |       |      
    |        |   |                  |            |    |                                                                                                               |       |    +--+-----+
+---+------+ |  ++---------+   +----+----------+ |    |                                                                                                             +-+----+  |    |Pillows |
| 2 Seater | |  | 3 Seater |   | Right Facing  | |    |                                                                                                             | Rugs |  |    +--------+
+----------+ |  +----------+   +---------------+ |    |                    +------------------------------------------------------------------------+               +------+  |              
             |                                   |    |                    |                                                                        |                         |              
             |                 +---------------+ |    |                    |  The order of the first le^el must be editable.                        |                     +---+----+         
     +-------+---+             | Left Facing   +-+    |                    |                                                                        |                     | Other  |         
     | Sofa Bed  |             +---------------+      |                    |                                                                        |                     +--------+         
     +-------+---+                                    |                    |   This is the inital Order:                                            |                                        
             |                                        |                    |                                                                        |                                        
             |                                        |                    |          1. Sofas                                                      |                                        
             |                                        |                    |          2. Sectionals                                                 |                                        
             |                                        |                    |          3. Sofa Beds                                                  |                                        
             +----------------------------------------+                    |          4. Armchairs                                                  |                                        
                                                                           |          5. Coffee Tables                                              |                                        
                                                                           |          6. Benches / Ottomans                                         |                                        
                                                                           |          7. Headboards                                                 |                                        
                                                                           |          8. Storage                                                    |                                        
                                                                           |          9. Accessories                                                |                                        
                                                                           |                                                                        |                                        
                                                                           |                                                                        |                                        
                                                                           |                                                                        |                                        
                                                                           +------------------------------------------------------------------------+                                        

```

@pom2ter On peut faire que une sous-categories pointers vers une categorie? (Voir Sofa Beds dans diagrame ASCII)

**Comment by pom2ter** [comment]
pas sur. peut-être possible en tweakant wp.
au pire ça peut être 2 catégories différentes pis on met chaque item dans les 2 catégories. il y aurait pas de différence entre les 2.
