### ISSUE TITLE
Catalog Billingualism.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#25]
On va pas maintenir deux product catalogs (En/Fr) donc il faut s'assurer que:
1. Woo nous permet des descriptions/titres billingues
2. Si 1 == non, est-ce que on a une solution?
3. Si 3 == non, plan/issue as btk plugin feature. (moi)

**Comment by pom2ter** [comment]
pour l'instant ça l'air être
1 - pas par lui-meme
2 - oui, mais
3 - voir plus bas

faut utiliser une combination de WPML (plugin multilangue) et ça https://wordpress.org/plugins/woocommerce-multilingual/  mais les 'requirements' sont pour la version payante de wpml qui est quand même de 79$ (il y a aussi une version à 29$ mais on a besoin des features de celle à 79$)

c'est le seul moyen d'avoir un catalogue multilangue avec des plugins existants

**Comment by pom2ter** [comment]
il y a une version a 29$ mais je sais pas si on a besoin des features de celle a 79$

**Comment by AKRFranko** [comment]
Ok. Je check vite fait si ya un PHP one-liner qu'on peut faire, sinon on se graye le plugin a $79.

**Comment by AKRFranko** [comment]
See about alt method for catalog only.

**Comment by AKRFranko** [comment]
La traduction de woocommerce se fait dans le plugin de base avec les fichers .po (bouttons, mots relies au UI ) 

Alors serieux pour ce qui est de l'aspect e-commerce il ne reste qu'a couvrir les descriptions/titres des produits. Donc j'ai une proposition:

```
Custom field dans admin (decription en/fr )

+ 

template hooks pour afficher. (overwrite description)
```

**Comment by AKRFranko** [comment]
@pom2ter Oh Oh Oh this? https://wordpress.org/plugins/woocommerce-poor-guys-swiss-knife/ ?!?!?!

**Comment by AKRFranko** [comment]
I have just successfully generated product using very little custom PHP code. To do this, I had to do a bit of reverse engineering and research on the internals of woocommerce product creation mechanism. 

From this I learned that:
- A product is a valid wordpress custom post type
- The additional attributes for a product are wordpress post meta

Therefore, since we only need title and description in french, I conclude that any plugin that handles multilingual post can really also do this for woocommerce products. 

Since you also override the the class rather than use the template as mentioned via your email, I think that is probably the best place to test this assumption.
