### ISSUE TITLE
Integrate/Design Placeholder Pages

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#26]
- Implement simple page with logo/title/description in pure html (with client provided document )
- Re-use that "design" to create similar static pages for 404.html 500.html etc...

These could be served by a very minimal static-only server and therefore must try to be as self-contained as possible ( embed css, js, and/or use 3rd party CDN assets)

**Comment by AKRFranko** [comment]
I think you did this with a plugin? If so and if it works, close ticket. Otherwise re-assign to me with answer.

**Comment by AKRFranko** [comment]
P.S: Dont worry about static stuff. If you made it dynamic I can easily copy paste the HTML either way.

**Comment by pom2ter** [comment]
l'erreur 404 est géré par wordpress. ça fonctionne comme n'importe quel post.
pour l'erreur 500 faudrait ajouté une ligne dans le .htaccess. ex: ErrorDocument 500 /errors/500.html
pour les 2 erreurs on pourrait ajouter une image custom sinon le client décidera.

**Comment by AKRFranko** [comment]
#54
