### ISSUE TITLE
Test/Learn new Workflow

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#3]
Tu va tester ton nouveau "workflow" ainsi:
1. Dans une console, tu pars
   
     grunt work
2. Tu ouvres ton editeur de code et tu edit (disons que tu mets `body{ background:red; }`)
   
     /src/themes/less/btk.less
3. A la sauvegarde te ton fichier, check dans ta console. 
4. Pas longtemps apres tu devrais voir un browser refresh avec un background rouge.

**Comment by AKRFranko** [comment]
Alors tu as compris que tout ce que tu @import dans btk.less va s'auto-magiquement compiler dans style.css et tout le JS va a s'auto-magiquement compiler dans /js/_btk.js ? Ou bien tu v iens de comprendre la la ?

**Comment by pom2ter** [comment]
je voyais les changements dans la console.
grunt-contrib-less converti en css pis grunt-contrib-copy copie tout les changements vers build.

**Comment by AKRFranko** [comment]
WINNING!
