### ISSUE TITLE
Understand Project Structure.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#4]
Go read the stuff I wrote in /docs 

Always read the stuff I write in /docs

/docs is the know!

P.S: You can also put stuff in /docs!

**Comment by pom2ter** [comment]
Jai réussi a me rendre jusqu'ici :O

**Comment by AKRFranko** [comment]
W00t W00t. Alors t'as eu un "Done, withour errors" ? Amazing!

**Comment by pom2ter** [comment]
le hic etait de faire fonctionner wordpress dans mamp et faire le lien vers build/themes/btk.
grunt m'a pas donné d'erreurs.

**Comment by AKRFranko** [comment]
Si j'amais ceci te cause des problemes eventuellement. Tu peut aussi overrider la variable "build_dir" dans ton config.json pour qu'il build ailleurs (ex: `"build_dir": "/Users/pom2ter/Sites/wordpress/wp-content/"` )
