### ISSUE TITLE
design issues

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#40]
- utilité du texte 'élément de base' et 'edb' avant de scroller (juste avoir un des 2 lorsqu'on est en haut de la page)
- mettre les images du carrousel en tant que background image (plugin)
- suggestion: avoir les icones social d'une autre couleur lorsque selectionnés
- gestion de la langue (sous-domaine ou /en/fr)
- news single black border wtf
- cacher le slug juste pour les autres users
- product listing: combien d'items ?
- ordre des items du catalogue
- pdf force download
- les design ont aucun titre de pages
- font-awesome pour tout? (fleches)

**Comment by AKRFranko** [comment]
FYI: returning customer/coupon http://docs.woothemes.com/document/create-a-coupon-programatically/

**Comment by AKRFranko** [comment]
~~utilité du texte 'élément de base' et 'edb' avant de scroller (juste avoir un des 2 lorsqu'on est en haut de la page)~~ 

TODO: Mets juste le logo 'edb' dans la nav, et sur le home page mets le texte en contenu (pas dans la nav, pour qu'il scroll out)

~~mettre les images du carrousel en tant que background image (plugin)~~ 

Oui, see: #44

~~suggestion: avoir les icones social d'une autre couleur lorsque selectionnés~~ `#666666`

~~gestion de la langue (sous-domaine ou /en/fr)~~ 

INFO: Si woocommerce supporte just un /en /fr alors je ferais un redirect. ex: fr.elementdebase.com -> elementdebase.com/fr (et peu importe le reste peut se regler avec mod_rewrite.)
__Leave your comments about this in #31 __

**news single black border wtf**

TODO: dont know yet, do like curent design (or whatever works best with other templates) easy to modify later.

~~cacher le slug juste pour les autres users~~ 

moved to: #46

~~product listing: combien d'items ?~~

5
~~ordre des items du catalogue~~

Recent first

~~pdf force download~~

Use the HTML5 "download" attribute

```
<a href="iphone_user_guide.pdf" download="iPhone User's Guide.PDF">click me</a>
```

 http://stackoverflow.com/a/18983688/261114

~~les design ont aucun titre de pages~~

TODO: Utiliser meme espace blanc que "element de base" (EDB dans le design, en haut de la premiere image) pour titre.

~~font-awesome pour tout? (fleches)~~

moved to: #47

**Comment by pom2ter** [comment]
Navbar will have both logo and full name and will grow in height to make that doable.
do not modify yet, we will get designers feedback for this.

from: #57

**Comment by AKRFranko** [comment]
FISHMO
