### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#42]
Structure
- header: 99%
- footer: 99%
- navigation: 90% - comportement du menu / localisation
- social stuff: 95% - ajout des liens sociaux
- login: 95% - comportement du formulaire
- sign up: 95% - comportement du formulaire

Contenu
- pages statiques header: 99%
- pages statiques footer: 99%
- page d'accueil: 95%
- catalogue: 95%
- order samples: 90% - envoie du form
- news: 99%
- confirmation: 95%
- 404: 99%

woocommerce
- mon compte: 90%
- produits - liste: 90%
- produits - détails: 80% - visited / sharing 
- categories: 95%
- panier: 95%
- checkout: 75% - shipping / payment
- reviews: 95%
- lookbook: 85% - unknown slider

**Comment by pom2ter** [comment]
header: assez avancé, j'me bats avec le menu
footer: fait,
social icons: correcte comme c'est la, p-e besoin d'un plugin si que le client puisse changer les liens lui-meme (seulement si nécessaire)

**Comment by AKRFranko** [comment]
:clap:

**Comment by pom2ter** [comment]
pages statiques + order samples sont fait. j'ai ajouté un plugin qui gère les liens medias sociaux

**Comment by pom2ter** [comment]
@AKRFranko  j'ai accès a production pour pouvoir ajouté les différents plugins pis toutes les 'pages' qu'on a besoin?

**Comment by AKRFranko** [comment]
Quand tu installes ex: woocommerce, il's t'offrent d'installer des pages 
![screen shot 2015-03-03 at 7 40 34 pm](https://cloud.githubusercontent.com/assets/7863981/6475859/35fbc506-c1dd-11e4-8fee-b4beb0899263.png)

On peut faire cela avec le theme sinon notre btk plugin facilement tu crois? C p-e la meilleure solution pour ce qui est des pages a long terme?

Et pour les plugins, je cherche encore. Si les settings du plugin sont en mysql grrrr... sinon au pire des pires ont peut faire un diff/patch pour automatiser:

local:

```
diff /copie-locale/le-plugin/settings.original.php /copie-locale/le-plugin/settings.modifies.php >  le-plugin-settings.php.patch
```

remote:

   patch /copie/remote/le-plugin/settings.php < le-plugin-settings.php.patch

 FYI: J'utilise diff/patch pour configurer les apache.conf php.ini etc.. it's a useful tool!

**Comment by pom2ter** [comment]
il y a une bonne chance que les settings des plugins soient en mysql. la plupart ajoute des tables dans la bd..

surtout pour un plugin comme woocommerce qui a plusieurs pages de parametres

creer des pages individuelles c'est moins important. mais faudra surement passé par l'admin pour creer un menu et changer l'ordre des pages

**Comment by AKRFranko** [comment]
Right. J'ai fait l'exercise hier et je crois bien que tu as raison, mais alors mon probleme est que des chagements "manuels" sa s'oublie. Tu as une idee comment ont devrait tracer/retracer ce genre de changements?

**Comment by pom2ter** [comment]
comparer la bd avec un backup? mais ça deviendrait overkill

**Comment by AKRFranko** [comment]
Non je voulais dire, comment garder un record clair des changements manuels pour pouvoir les reproduire "verbatim" a la main.

**Comment by AKRFranko** [comment]
FYI specified by client when detailing mockups: Everything is lowercase, no capital letters (see mockups).

**Comment by pom2ter** [comment]
j'avais remarqué

**Comment by AKRFranko** [comment]
Eagle eyes!

**Comment by AKRFranko** [comment]
Ironically, this is ticket #42 and for the meeting I'm having later, this ticket actually DOES hold the answer to life, the universe and everything (although it be a very tiny universe)

**Comment by AKRFranko** [comment]
@pom2ter Close this ticket and start fresh?

**Comment by pom2ter** [comment]
j'va en créer un nouveau tantot
