### ISSUE TITLE
Create Small Caroussel Plugin or Tweak whatever bootstrap has.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#44]

**Comment by pom2ter** [comment]
http://getbootstrap.com/javascript/#carousel

**Comment by AKRFranko** [comment]
> Accessibility issue
> The carousel component is generally not compliant with accessibility standards. If you need to be 
> compliant, please consider other options for presenting your content.

I can do a bit better, easy.

**Comment by AKRFranko** [comment]
FYI: we dont "NEED" to be compliant in this case

**Comment by pom2ter** [comment]
ça me dérange pas de pas être compliant jusqu'a un certain point.

**Comment by AKRFranko** [comment]
Generalement dans ces cas, mon idee est que le default devrait etre qqc de poche mais mais qui marche pour tous ex: une image seule. Et tu batis tout le fancy stuff en DHTML.

**Comment by AKRFranko** [comment]
I+Client like what we have, good enough? Close this ticket?
