### ISSUE TITLE
wp is not defined

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#45]
la plupart du js fonctionne pas a cause de cette erreur. pour l'instant je peux pas trouver la cause.

aussi, il y a une couple de plugin qui ajoute des classes dans la balise html ce qui est correct. sauf que les classes sont répété 3-4 fois. ça pas l'air d'affecté quoi que ce soit mais c'est quelque chose qu'on devra checker.

**Comment by AKRFranko** [comment]
Le theme _s essaye de supporter le theme customization.

Selon cette ligne: https://github.com/AKRFranko/btk/blob/master/src/themes/btk/inc/customizer.php#L24 

Il charge le ficher dans notre theme `customizer.js` qui a comme dependance un ficher interne a wordpress "customize-preview" . wp doit exister la bas. 

Mon premier instinct fut de faire qqc du genre "if( typeof wp === 'undefined' ) return; dans custmoize.js mais pour quelquon'que raison, marchait pas....

Alors j'ai pense un peu plus fort pis au fond, on s'en sert pas... pour le moment alors:

https://github.com/AKRFranko/btk/commit/8e04f5174752f3ef97a46aae047afb5934d0fd3c

Mais sa marchais tjrs pas... alors j'ai fait les 2

https://github.com/AKRFranko/btk/commit/fb049a4ff74d835683ee445387b0642dc9757b7b

Je crois qu'on a un grunt problem, j'ai du manuellement effacer _btk.js pour que mon changement ecrase  celui dans build... hmm...
