### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#48]
question: c'est quoi la syntaxe pour pouvoir écrire de quoi en jquery?
juste écrire quelque chose comme  $(".selector").click(function() etc ,  comme je fais d'habitude, me donne toujours une erreur 'undefined is not a fonction'

**Comment by AKRFranko** [comment]
Ah-HA! no conflict mode, jQuery n'exporte pas `$` sur `window` dans ce cas, mais `window.jQuery` existe...

alors wrap ton code dans un module pattern et passe `jQuery` a `$`:

```
!( function( $  ){

    /* Use $ like you normally would, write your codes here. */

})( jQuery )
```
