### ISSUE TITLE
liste de plugin WP

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#49]
Liste de plugin wp que j'utilise localement sans compter woocommerce
- Contact form 7  - gérer des formulaires de contact (pour l'inscription au newsletter / order sample)
- LiveReload Snippet - pas utile en production
- Optimize Database after Deleting Revisions - efface les anciennes versions de page et articles et optimize la bd, c'est le fun a avoir
- Simple Page Ordering - trier les 'pages' utile pour les menus
- Social Media Feather - gérer les liens réseaux sociaux
- WP Maintenance Mode - redirige vers un landing page pendant qu'on fait une maintenance

**Comment by AKRFranko** [comment]
Contact form 7 - installed
LiveReload Snippet - whatever
Optimize Database after Deleting Revisions - wp-cli does this also.
Simple Page Ordering - meh
Social Media Feather - installed
WP Maintenance Mode - will do at apache level in prod deploy process.
