### ISSUE TITLE
Pour le fleche qui tombent sur le tapis.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#50]
Une combinaison de ceci: 

```
.caption.center {
    background-image: linear-gradient( rgba(0,0,0,0) 90%, rgba(0,0,0,0.2));
}
```

Et avoir le bon icone pour les fleches, devrait regler le probleme visuellement.

**Comment by AKRFranko** [comment]
Tweaked a bit, the example I gave (90%) works better on .bx-viewport than .bx-pager

**Comment by AKRFranko** [comment]
It's a matter of finding the righnt element, doesnt seem to work OR we have a grunt/deploy problem...

**Comment by pom2ter** [comment]
j'm'en allais dire que je vois pu les fleches :p

**Comment by pom2ter** [comment]
ça devrait pas fonctionner sur bx-viewport vu qu'il y a un élément par-dessus qui cancelle l'effet

**Comment by pom2ter** [comment]
jai remis l'effet sur bx-pager en attendant
