### ISSUE TITLE
Need correct key for WPML

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#52]
Pour utiliser WPML en local et dev on a besoin d'une clé. Ca l'air d'être généré a partir du url ce qui voudrait dire que local et dev et production auront pas la meme clé

**Comment by AKRFranko** [comment]
Grrr. Ok. Sorry, avais d'autre petits probelemes a regler server-side je te reviens la dessus ASAP!

**Comment by AKRFranko** [comment]
Essaye de mettre sa dans ton /etc/hosts 

```
localhost.elementdebase.com  12.0.0.1
```

configure ton blog local pour utiliser cette addresse...

  License Key: hvuDDZvwFv
