### ISSUE TITLE
Correction For Home Page Template

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#55]
En ce moment le home page a un caroussel en haut et plusieurs mini caroussels en dessous. 

On avait parle toi et moi que tu l'avais fait ainsi a cause que les fleches que tu voyais etaient "logiquement" des fleches de "next picture"... 

J'avais garde ta version a fin de bien illustrer ton point et effectivement tu avais raison.
# Changements a apporter immediatement:

Ne ne sont pas des caroussels, c'est just le featured image, enlever la fleche (pour le moment) et quand on click dessus on va vers le post (behavior: comme j'ai fait su mocoloco.com   http://mocoloco.com/)

Mets pas trop de travail sur les hover effects etc, c'est retombe dans la cour des designers.
# Changements qui viendront apres le design review:

On affichera un terme de taxonomie (tag &&|| categorie) du post

ex:

[TRADE]   kale lasn strikes again ( blog post about designer )
[DESIGN]  new textiles, new textures (blog post sur sur industrie)
[NEWS] edb is now online (blog post about edb)

**Comment by AKRFranko** [comment]
Priority ticket!

**Comment by pom2ter** [comment]
cest fait. j'ai laissé les flèches parce que ça parait mieux et pour garder le même design que les autres pages

**Comment by pom2ter** [comment]
une chose a savoir est si les 3 posts sont les plus récentes de 3 catégories différentes (collection ,news, article) ou si c'est juste les 3 plus récents tout court indépendamment des catégories. dans ce cas faudrait savoir quelles catégories pourraient avoir ses posts s'afficher sur la homepage
