### ISSUE TITLE
Investigate/Fix Home Page Flickering on Some Devices

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#56]
Sur le iPad et le moyenement vieux iPhone de notre client, le home page fait un genre de reverse-FOUC (http://en.wikipedia.org/wiki/Flash_of_unstyled_content) 

iPad: On vois brievement une image qui load et "poof" blank homepage avec rien. 
iPhone: Semblable, mais desfois on vois la page offset ver le haut.

Je n'ai pas fais d'investigataion profonde mais voici quelques tips:
1. Avant tout, tente de reproduire le probleme dans IOS simulator ou autre. Si tu peut pas reploiquer le bug, sert a rien d'essayer de le repliquer.
2. Si tu est capable de reproduire, trouves-en l'origine.
3. Si tu peut le reparer, repares-le, sinon fais moi un raport de la situation et j'y plongerai.

**Comment by AKRFranko** [comment]
If it has to do with image loading then maybe this 1,2,3 punch does the trick:
1. https://github.com/AKRFranko/btk/issues/8
2. link lowres images in HTML
3. use javascript to load heavier images in place of lowres once

**Comment by AKRFranko** [comment]
Could also be related to wp-admin bar conflicting with bootstrap.

**Comment by pom2ter** [comment]
je vois pas la page disparaitre une fraction de seconde mais je remarque que sur ipad en scrollant la page et apres revenir sur la page d'accueil que la bar wp disparait jusqua temps que tu rescroll.
p-e que le fait d'avoir 1 slider au lieu de 4 sur la homepage aide.

ca peut etre aussi du au plugin slider qui load tous les images et bati le carousel

**Comment by pom2ter** [comment]
jai enlevé la bar wp sur mobile parce que pas pratique et gaspille de l'espace

**Comment by AKRFranko** [comment]
Ouais. D'habitude je la mets carrement off! (Go ahead si tu veut)

**Comment by AKRFranko** [comment]
Working on this... Finalement c'est une combinaison de
- Slider loads all images twice ( background + <img>)
- Images are big
- Loading of images is not deferred.

**Comment by AKRFranko** [comment]
Is it IOs bug? Is it fixed?

**Comment by pom2ter** [comment]
bug avec safari qui est corriger sur une version plus récente.
pas reproductible a moins d'avoir un vieux ipad/iphone

**Comment by AKRFranko** [comment]
Je suis capable reproduire dans ios simulator!! W00t! Je check sa! 

![screen shot 2015-04-15 at 7 12 45 am](https://cloud.githubusercontent.com/assets/7863981/7157582/0ba53b4c-e33f-11e4-956f-5d9bf2a167be.png)

**Comment by AKRFranko** [comment]
A date je vois le images 1 seconde et ensuite qqc fait disparaitre toute la page, Je suspecte JS. 

Anyways. ME semble un peu overkill bx-slider.js la que j'ai fouille dans leur source, je vais essayer autre chose.
