### ISSUE TITLE
Navbar will have both logo and full name and will grow in height to make that doable.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#57]
FYI, do not modify yet, we will get designers feedback for this. Keeping you in the loop. Close this ticket when acknowledged.

**Comment by AKRFranko** [comment]
Confirmed. Do exactly like it looks like in the design but no hidding text:

![screen shot 2015-04-02 at 9 17 43 am](https://cloud.githubusercontent.com/assets/7863981/6964647/318d199a-d919-11e4-9002-9a610568cf67.png)

**Comment by pom2ter** [comment]
je suis pas d'accord avec cette décision. on perd de l'espace surtout sur mobile.

**Comment by pom2ter** [comment]
tu peux voir le résultat

**Comment by AKRFranko** [comment]
Effectivement. Ce qui se passe ici (je crois) c'est que des fois les 
gens "comprennent" pas vraiment ces problematiques jusqu'a ce quils le 
voient pour de vrai dans un device. Alors surement que sa va changer 
mais pour le moment, nous avons accomplis notre mission.

Thanks!
