### ISSUE TITLE
Winning

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#58]
In order to win we need one thing, everything else is fluff and easy to do:

   If I can place an order on the website and get an email detailing the order then we have accomplished what we have said we would do. 

On your local machine right now, how close are we to winning? What's missing?

**Comment by pom2ter** [comment]
il reste le paiement i.e. ce qui se passe quand tu clique sur checkout. donc utiliser/installer un gateway et traiter les infos qu'on recoit. pis modifier les emails au besoin.
(il y a la page checkout a integrer)

il y a deja quelques gateway par défauts mais j'aime mieux que toute ce fasse sur un site externe comme paypal (qui fait partie des gateway installés par defaut). j'aimerais mieux pas que le client entre ses infos de cartes de crédit sur notre site pis qu'on ait a gérer ça

**Comment by AKRFranko** [comment]
D'accord. Je crois que nous allons vers moneris. J'aurai cette conversation genre la semaine prochaine alors si tu as remarques now is the time! (Paypal noted)

**Comment by pom2ter** [comment]
l'extension moneris coute 79$
http://www.woothemes.com/products/moneris-gateway/
