### ISSUE TITLE
Make the background color of login etc. menus easily customizable.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#59]
I have a gut feeling (through conversations) that this color will change often. Can you make it into a wp theme variable so that it can be easily changed in the admin? (bonus, optional: per/menu color )

**Comment by pom2ter** [comment]
techniquement c'est pas une couleur mais une image png transparente. j'utilise l'image parce que en utilisant la transparence en css ça aurait affecté tout le contenu.

aussi, une couleur de background est pas suffisant il faudrait une couleur pour le texte sinon le texte va rester blanc quelque soit la couleur bkg qu'on choisie.

**Comment by AKRFranko** [comment]
Ha! Voici une opportunite parfaite d'upgrader ton kung fu!

Comment avoir un background de couleur, transparent, en CSS, sans images:

   Specifie la regle deux fois.

```
background:#000; /* fallback to flat color for older browsers */
background:rgba(0,0,0,0.5);  /* old browsers will not understand this, so will use previous one */
```

Utilise pas `opacity` pour ces choses utilises rgba ( http://caniuse.com/#search=rgba )

Situations plus complexes, ou besoin de mettre un CSS gradient, image background etc... 

```
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Ex:</title>
      <style type="text/css">

        #colored-area{
          /* So we can use absolute within, must have layout */
          position:relative; 
          color:#fff;
          padding:5px;
        }

        #colored-area:before{
          /* Where the magic happens */
          content:'';
          position:absolute;
          z-index:-1;
          display:block;
          top:0;left:0;
          width:100%;
          height:100%;
          background:rgba(0,0,50,0.3);
        }

      </style>
    </head>
    <body>
      <div id="colored-area">
        <p>Content that should not be transparent</p>
        <button>FTW!</button>
      </div>
    </body>
    </html>
```

**Comment by AKRFranko** [comment]
Pour la couleur du texte en contrast avec le BG faut pas oublier que Thien (le client) est un designer et il comprendra ceci mais voici comment moi je reglerai ce probleme generiquement... 

select background color:  `<color picker>`
select foreground: white `<checkbox>`  black `<checkbox>`
