### ISSUE TITLE
Install Your Browser Detection Dependency Via Bower

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#6]
J'ai deja mis bootstrap, trouve ton bidule qui mets des classes css pour ton browser detect et essayes de l'installer par l'entremise de notre bower.json (si pas supporte par bower, c'est quand meme faisable voir plus bas ) pour que quand tu fasses `grunt build`, `grunt`, `grunt work` ou bien `grunt watch` le code se retrouve bel et bien dans le fichier /build/themes/btk/js/_btk.js 

Si une librairie JS n'as pas de bower.json tu peut quand meme le faire, bower.json permet de specifier un github url etc...... voici des pistes:

https://github.com/bower/bower.json-spec#dependencies
https://github.com/sapegin/grunt-bower-concat#mainfiles

**Comment by pom2ter** [comment]
Ok pour le moment ça ca marche pas...

La libraire est ici : https://github.com/isarmstrong/css_browser_selector

dans bower.json j'ajoute ça dans les dépendances : "css_browser_selector": "https://github.com/isarmstrong/css_browser_selector"

ça l'installe mais pas avec les fichiers que je veux.

dans le gruntfile j'essaie de mettre ce que jai besoin dans la section bower_concat mais il y a quelque chose que je catch pas et ça marche pas

**Comment by AKRFranko** [comment]
T'as commit/push?

**Comment by pom2ter** [comment]
c'est fait

**Comment by AKRFranko** [comment]
Fixed! (En passant, c'est pas dans _btk.js mais bien dans _bower.js, sorry for that)

See: https://github.com/AKRFranko/btk/commit/00d2b2db8d9b73aa2eaa60dbd67c739e7dc5b588

**Comment by pom2ter** [comment]
faque fallait ajouter .git dans bower.json pour qu'il installe tous les fichiers? au lieu d'Avoir juste le fichier index

**Comment by AKRFranko** [comment]
Ouais, c'est dans la facon que Github fonctionne:

```
  https://github.com/username/projectname     == Handled by HTTP(s) server
  https://github.com/username/projectname.git  == Handled by GIT server through HTTP(s) protocol
  git://github.com:username/projectname.git    == Handled by GIT server through ssh protocol
```
