### ISSUE TITLE
Need icon hook in carousel counter

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#60]
The "pipe" character seems to be a hard-coded mechanism of the carousel:

![screen shot 2015-04-01 at 9 36 50 am](https://cloud.githubusercontent.com/assets/7863981/6942064/e76d8550-d852-11e4-867f-8c816af56f17.png)

We need to put a thinner icon in there, the line is too thick.

**Comment by pom2ter** [comment]
le caractère était en gras, pu maintenant. c'est un peu moins épais mais p-e toujours trop épais.
c'est pas hardcodé, ça fait partie des options quand tu l'initialise avec jquery 
genre  $('.slider').bxSlider({ pagerShortSeparator: ' | '; });

**Comment by AKRFranko** [comment]
Gud! Will review when time comes. Good enough for now.
