### ISSUE TITLE
script bugs

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#64]
j'imagine que tu utilise un nouveau script pour déployer edb. sauf que ça reset tous les settings des plugins et on peut pas les mettre a jour a partir de l'admin wp. (edit: ni les effacer)
cause probable: probleme de permissions (pour ce qui est de les mettre a jour / effacer pas pour les settings qui reset)

**Comment by AKRFranko** [comment]
OK, je m'attendais un peu a cela. Skype?
