### ISSUE TITLE
Menu close icon should inherit user selected color.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#66]
![screen shot 2015-05-19 at 11 54 41 am](https://cloud.githubusercontent.com/assets/7863981/7707480/0891ac7a-fe1e-11e4-9a9d-b94b9057ad51.png)
![screen shot 2015-05-19 at 11 53 12 am](https://cloud.githubusercontent.com/assets/7863981/7707482/0895140a-fe1e-11e4-8cb6-c7a204ecfdbe.png)
![screen shot 2015-05-19 at 11 52 12 am](https://cloud.githubusercontent.com/assets/7863981/7707481/0892e04a-fe1e-11e4-864e-a3da5d4f38b2.png)

Or else we might get a nasty hidden button if background is same as icon.

**Comment by pom2ter** [comment]
le gris est du au a:hover et/ou a:visited

**Comment by AKRFranko** [comment]
Ouais, mais c'etais un problem waiting to happen. Good job!

**Comment by AKRFranko** [comment]
FYI: Dans un cas comme ceci, si disons tu voulais un "hover" state, tu pourrais jouer avec soit `opacity` (comme mes triangles temporaries dans le product menu) ou bien un genre de "halo" avec `box-shadow`
