### ISSUE TITLE
splash page bug

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#68]
la splash page s'affiche sur toute les pages a chaque refresh. peut-etre que c'est ce que veut le client mais si il est pour montrer le site a ses investisseurs , pas sur qu'il aimerait la voir a chaque page. ça ferait pas très winner

**Comment by AKRFranko** [comment]
Not a bug. C'est pour illustrer l'argument que tu viens de stipuler. Si je mets du temps la dessus je fais juste travailler sur une feature imaginaire qui ne reflete pas la realite du site.

Tu peut run ce javascript une fois sur le site pour plus la voir TOI:

localStorage.setItem('edb-splash:devon', 'true' );
