### ISSUE TITLE
slider plugin change

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#69]
je peux pas switcher le slider sur la page produit. la manière que le plugin va chercher les images ne s'applique pas pour cette page. chaque produit a une 'feature image' mais aussi une gallerie ou on peut ajouter les autres images du produit. faudrait changer le plugin pour en tenir compte.

**Comment by AKRFranko** [comment]
Ouaip. Au fond c'est juste un fonction dans functions.php je crois qui retournes les images. C'est un hook  ajax. 

see: https://github.com/AKRFranko/btk/blob/master/src/themes/btk/functions.php#L74
