### ISSUE TITLE
Start Prepping Theme To Your Liking

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#7]
Je sais qu'on a pas encore les maquettes, mais je sait aussi que tu as certaines habitudes etablies dans ton skill-set, alors profites-en pendant qu'on est pas dans le rush pour tester que bootstrap fonctionne a ton gout, que tes outils front-end sont bel et bien fonctionels, commence a mettre /src/themes/btk un peu plus a ta saveur personelle etc... c'est ton terrain de jeu principal.

**Comment by AKRFranko** [comment]
PS: Si tu veut quand les tickets sont vagues ainsi, tu peut le fermer, et t'en ouvrir des plus concrets. Fais juste laisser une reference dans les autres ex: #7

**Comment by pom2ter** [comment]
tout semble fonctionner
