### ISSUE TITLE
Slider Font Tweaking.

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#71]
Apparently the font for titles on top of slider images doesn't "feel" the same as in the photoshop. We think  maybe it's too small?

**Comment by pom2ter** [comment]
je l'ai tweaké un peu. la grosse différence avec la maquette c'est qu'ils utilisent une autre police 'executive' qu'on a pas

**Comment by AKRFranko** [comment]
Got angry, made changes!
