### ISSUE TITLE
Price Display

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#72]
For some reason there's too much information in the "price" html... Investigate, remove/tweak unwanted information.

**Comment by AKRFranko** [comment]
Re-assigned to me, I think it's data import problem.

**Comment by AKRFranko** [comment]
added variation _regular_price in data import, tweaked look with css.

**Comment by pom2ter** [comment]
j'pense pas t'avais besoin de faire tout ça mais bon.

**Comment by AKRFranko** [comment]
Non mais je trouvais que dans le futur sa pourrait etre utile d'avoir les prix et un CSS hack sa risque pas de venir en conflit avec woocommerce behind the scenes.
