### ISSUE TITLE
Implement Proper scrolling in hamburger menu

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#73]
I did a similar fix for the splash page. Body needs to be "fixed" when menu is open and menu must be made scrollable. Then body must be reverted to position: "static" or whatever it was when the menu is closed. Re-assign to me if it's not and obvious fix.

**Comment by AKRFranko** [comment]
Via Harry:

Here is a screenshot from iPhone 5s, iOS 8.2, Safari browser (default).

I opened all the submenus to make the menu as long as possible. Everything scrolls ok, but the very bottom is unreachable because of the browser bottom nav (as is shown). It's possible to tap the screen to make the bar go away, but for inexperienced users they may not know how.

![img_9122](https://cloud.githubusercontent.com/assets/7863981/7864228/ce4b7646-052e-11e5-9bf0-63a1617a73a1.jpg)

Here is a screenshot from iPhone 4s, iOS 7.1.2, Safari browser (default). This is the same config as Thien's phone.

This setup for scrolling does not work, it's impossible to scroll down (see screenshot). And as you noted, attempting to scroll will scroll the page underneath the menu.

![img_9123](https://cloud.githubusercontent.com/assets/7863981/7864246/ef8a9f4e-052e-11e5-84a8-a950feab560b.JPG)

**Comment by AKRFranko** [comment]
OTTOMH the first one is easy, compensate for the browser's bottom nav by adding it's height to the bottom padding of the scrollable pane. ( in other words: add lots of bottom padding)

**Comment by pom2ter** [comment]
mieux mais pas parfait.
pas sur de comprendre la 2e image

**Comment by AKRFranko** [comment]
J'ai juste regarde le code du commit et dans chrome mais it looks good, j'attends confirmation du client avant de closer.

**Comment by pom2ter** [comment]
jai du changé de quoi parce que l'autre commit a ajouté un bug sur tablette/desktop. je sais pas si ca va affecter le iphone. ios simulator a l'air correct.
