### ISSUE TITLE
typekit question

### ISSUE THREAD

**Issue by pom2ter** [AKRFranko/btk#74]
est-ce que ça inclut aussi 'theinhardt' ? elle est supposé être la police par défaut sauf pour les en-tete.

**Comment by AKRFranko** [comment]
Nope. Theinhardt et Executive sont des fonts de la fondrie "optimo". D'apres moi, les designers chez Paprika sont en amour avec Optimo et l'amour rends tellement aveugle qu'ils oublient que j'ai dis "must be available on typekit". Apres discussion avec le client, il est d'accord avec une approche "whatever is closest" a cause que LUI il comprends nos directives ;)

Le OK pour theinhardt est ce que tu as deja. On laisse "theinhardt" dans la declaration CSS pour que Paprika voient bien ce qu'ils veulent voir. Pendant ce temps, toi, moi et le client on avance par en avant.
