### ISSUE TITLE
Single Product Slider extinct?

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/btk#80]
Single product slider seems to have gone the way of the dodo (http://en.wikipedia.org/wiki/Dodo)?  

I suspect there's a logic error in:

 https://github.com/AKRFranko/btk/commit/1467e82387eca1aeb4010d823e0b9d01f781ddc6

I know for a fact that current products in database have more than one image. Maybe I should note that I attach them as wordpress images to the product post, I do NOT import them as any kind of special woocommerce-specific gallery or data type.

**Comment by pom2ter** [comment]
j'ai enlevé le slider si il y a juste une image parce qu'il y a aucun intêret a mettre un carousel si ya rien a carousseler.  les autres images doivent etre ajouter dans le 'product gallery' . tu peux checker dans le backend pour comprendre

**Comment by pom2ter** [comment]
en fait jai pas 'enlever' le slider. jai mis une condition que si ya juste une image, affiche la sinon utilise le slider

**Comment by AKRFranko** [comment]
Hmmm... Je peut les ajouter dans le "product gallery" je crois, je vais essayer.

**Comment by AKRFranko** [comment]
Not deployed yet, fixing other stuff.
